apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  namespace: default
  labels:
    app: hello-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: mycontainer
        image: mydokcer/image
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: anj-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: hello-app
  ports:
  - port: 8080
    targetPort: 443
    nodePort: 55677